### ISSUE TITLE
Make Bluesky Scans Trigger `Count` Instead of Relying on the Numbers from `AutoCount` 

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#204]
Seems as if `lup` is relying on the scaler's autocount mode to trigger a count.  Instead, `lup()` should put the scaler into `OneShot` mode and trigger the count at each step, then put the scaler back into `autocount` mode.

The configuration of scaler mode is a good thing to add to `stage_sigs`.

**Comment by qzhang234** [comment]
Right now we can't do any scans with the scaler trigging acting like this:

<img width="618" alt="Screen Shot 2020-07-14 at 12 04 26 PM" src="https://user-images.githubusercontent.com/48140482/87454877-35820300-c5ca-11ea-8e17-81e23b482e14.png">

**Comment by qzhang234** [comment]
<img width="627" alt="Screen Shot 2020-07-14 at 12 18 19 PM" src="https://user-images.githubusercontent.com/48140482/87456186-3156e500-c5cc-11ea-8a83-80d89024785c.png">

**Comment by prjemian** [comment]
Back at 1 pm

**Comment by qzhang234** [comment]
Got it. Also the scan works fine in Spec, no spikes.

<img width="803" alt="Screen Shot 2020-07-14 at 12 21 48 PM" src="https://user-images.githubusercontent.com/48140482/87456507-a7f3e280-c5cc-11ea-9206-1b7eb217cef7.png">

**Comment by prjemian** [comment]
Did you try a `lup()` _scan_ after you ran in SPEC?  I suspect the scaler (in EPICS) is misconfigured and SPEC might fix it.  The scaler has to pass the test of `RE(bp.count([pind2], num=5))`.

Second guess is that the bluesky session has misconfigured its scaler object.  If that is the case, a restart of bluesky should fix it.

**Comment by qzhang234** [comment]
I tried both scanning after Spec scan and restarting Bluesky, and the problem is still there.

By the way I think this is the first time I've seen Bluesky doing this. Back when I wrote the wiki page everything was working just fine ...

**Comment by prjemian** [comment]
It happened just as I was asking why the tuning scan showed such irregular signal when the count rate was high.  You adjusted a couple things in the GUI screen and we have not been the same since.

**Comment by prjemian** [comment]
I could not resolve (small font) what was changed.  I've got a meeting at 3:30.  After that can we meet?  I'll send you a note on Teams.

**Comment by prjemian** [comment]
In bluesky, the symbol `pind1` is a scaler *channel*, an EpicsSignalRO that has no notion of `.trigger()`.  It won't pay attention to any count time.  To scan and trigger the scaler at each point, need to use the `scaler` device as the _detector_.  It helps to set the count time and mode, so this is what you want:

```
scaler1.stage_sigs["preset_time"] = 1
scaler1.stage_sigs["count_mode"] = "OneShot"
scaler1.select_channels(['pind1'])   # just the pind1 channel (and the timebase)
RE(bp.count([scaler1], num=5))
scaler1.select_channels(None)    # selects all named channels again
# optional steps
del scaler1.stage_sigs["preset_time"]
del scaler1.stage_sigs["count_mode"]
```

**Comment by prjemian** [comment]
```
In [50]: pind1                                                                                                                                        
Out[50]: EpicsSignalRO(read_pv='8idi:scaler1.S2', name='pind1', parent='scaler1_channels_chan02', value=509.0, timestamp=1594764760.221152, auto_monitor=False, string=False)
```

**Comment by prjemian** [comment]
Technically, `pind1.trigger()` exists but does no useful work:

```
In [52]: pind1.trigger??                                                                                                                              
Signature: pind1.trigger()
Source:   
    def trigger(self):
        '''Call that is used by bluesky prior to read()'''
        # NOTE: this is a no-op that exists here for bluesky purposes
        #       it may need to be moved in the future
        d = Status(self)
        d._finished()
        return d
File:      ~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/signal.py
Type:      method
```

**Comment by prjemian** [comment]
revised  `lup()`:

```
def lup(scaler_name,
        motor_name,
        pos_start,
        pos_stop,
        num_pts,
        count_time):
        
    yield from sb() 
    scaler1.stage_sigs["preset_time"] = count_time
    scaler1.stage_sigs["count_mode"] = "OneShot"
    scaler1.select_channels([scaler_name])
    yield from bp.rel_scan(
        [scaler1, lakeshore],
        motor_name,
        pos_start,
        pos_stop,
        num_pts,
        ) 
    scaler1.select_channels(None)    # selects all named channels again
    del scaler1.stage_sigs["preset_time"]
    del scaler1.stage_sigs["count_mode"]
    yield from bb()
```

**Comment by qzhang234** [comment]
Worked like a charm. Thanks Pete!

<img width="627" alt="Screen Shot 2020-07-14 at 6 08 07 PM" src="https://user-images.githubusercontent.com/48140482/87484887-fc16bb00-c5fc-11ea-8623-d56c0ec70e3e.png">

**Comment by prjemian** [comment]
Goody!
